// Package main is the wasm-tool CLI shim — the bridge between the
// daemon's tooling.Executor and the Claude Code subprocess that the
// CLI-backend tier (`backend = "cli"`, the default for the bundled
// haiku/sonnet/opus tiers) spawns to run user prompts.
//
// The API-backend tier path (#423 + #425) dispatches wasm-tool bundles
// through `provider.ToolLoop` → `Executor.Execute` directly inside the
// daemon. The CLI tier can't do that because Claude Code drives tools
// by running binaries on PATH, not by calling Go functions. Without
// this shim, every wasm-tool listed in toolbox.md would be invisible
// to Claude Code or — worse — the LLM would hallucinate a response,
// the failure mode that bit the #423 smoke (#425's discovery).
//
// Invocation forms (mirrors the toolbox.md entries generated by
// memory.GenerateToolbox):
//
//	wasm-tool <id> '<json-args>'        # args inline
//	echo '<json-args>' | wasm-tool <id> # args on stdin (preferred for long bodies)
//	wasm-tool <id>                      # no-args tools (defaults to "{}")
//
// Output: stdout receives the tool's marshalled result verbatim — for
// wasm bundles, that's the JSON form of capability.Output.Data; for
// native tools, whatever the tool prints. stderr carries dispatch
// failures (socket unreachable, tool not found, daemon HTTP error).
// Exit codes:
//
//	0 — daemon returned a clean result (is_error=false)
//	2 — daemon returned is_error=true (tool ran, signalled failure)
//	3 — transport / socket / malformed-response error (dispatch failed)
//	64 — usage error (no tool id passed)
//
// Authentication is socket-presence: ALF_TOOLS_SOCK is read-only and
// mode 0660 group-alf inside the container, so only processes the
// daemon launches see it. No bearer token is involved on this path.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"time"
)

const (
	exitOK         = 0
	exitToolError  = 2
	exitTransport  = 3
	exitUsage      = 64
	defaultTimeout = 60 * time.Second
)

type request struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

type response struct {
	Output       string `json:"output"`
	IsError      bool   `json:"is_error,omitempty"`
	ExitCode     int    `json:"exit_code,omitempty"`
	ErrorMessage string `json:"error_message,omitempty"`
}

func main() {
	os.Exit(run(os.Args[1:], os.Stdin, os.Stdout, os.Stderr))
}

// run is the testable entry point. Splitting main allows tests to
// drive the binary without spawning a subprocess and to capture exit
// codes via the int return value.
func run(args []string, stdin io.Reader, stdout, stderr io.Writer) int {
	if len(args) == 0 || args[0] == "-h" || args[0] == "--help" {
		fmt.Fprintln(stderr, "usage: wasm-tool <id> [<json-args>]")
		fmt.Fprintln(stderr, "       echo <json> | wasm-tool <id>")
		fmt.Fprintln(stderr, "Reads ALF_TOOLS_SOCK (set by the daemon).")
		if len(args) == 0 {
			return exitUsage
		}
		return exitOK
	}

	name := args[0]
	var argsJSON string
	switch {
	case len(args) >= 2:
		argsJSON = args[1]
	default:
		// No inline args — try stdin. Empty stdin is fine; the daemon
		// substitutes "{}" so no-args tools work without ceremony.
		body, err := io.ReadAll(stdin)
		if err != nil {
			fmt.Fprintf(stderr, "wasm-tool: read stdin: %v\n", err)
			return exitTransport
		}
		argsJSON = string(bytes.TrimSpace(body))
	}

	sock := os.Getenv("ALF_TOOLS_SOCK")
	if sock == "" {
		fmt.Fprintln(stderr, "wasm-tool: ALF_TOOLS_SOCK not set (run from a daemon-launched subprocess)")
		return exitTransport
	}

	resp, err := invoke(sock, name, argsJSON)
	if err != nil {
		fmt.Fprintf(stderr, "wasm-tool: %v\n", err)
		return exitTransport
	}

	// Print the tool output (stdout). Even on tool errors we print the
	// payload — the executor sets is_error and the message duplicates
	// in ErrorMessage when applicable, but the body often holds the
	// useful diagnostic (stderr capture, stack trace).
	if resp.Output != "" {
		fmt.Fprintln(stdout, resp.Output)
	}
	if resp.IsError {
		if resp.ErrorMessage != "" {
			fmt.Fprintf(stderr, "wasm-tool: tool reported error: %s\n", resp.ErrorMessage)
		}
		return exitToolError
	}
	return exitOK
}

func invoke(sockPath, name, arguments string) (response, error) {
	client := &http.Client{
		Timeout: defaultTimeout,
		Transport: &http.Transport{
			DialContext: func(_ context.Context, _, _ string) (net.Conn, error) {
				return net.Dial("unix", sockPath)
			},
		},
	}

	body, err := json.Marshal(request{Name: name, Arguments: arguments})
	if err != nil {
		return response{}, fmt.Errorf("marshal request: %w", err)
	}

	req, err := http.NewRequest("POST", "http://tools/api/tools/invoke", bytes.NewReader(body))
	if err != nil {
		return response{}, fmt.Errorf("build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-Requested-With", "wasm-tool")

	httpResp, err := client.Do(req)
	if err != nil {
		return response{}, fmt.Errorf("dispatch via %s: %w", sockPath, err)
	}
	defer httpResp.Body.Close()

	rawBody, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return response{}, fmt.Errorf("read response: %w", err)
	}
	if httpResp.StatusCode != http.StatusOK {
		return response{}, fmt.Errorf("daemon returned HTTP %d: %s", httpResp.StatusCode, bytes.TrimSpace(rawBody))
	}

	var r response
	if err := json.Unmarshal(rawBody, &r); err != nil {
		return response{}, fmt.Errorf("malformed daemon response: %w (raw=%q)", err, rawBody)
	}
	return r, nil
}
